[project]
name = "cd12380-data-pipelines-with-airflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "apache-airflow>=3.0.3",
    "apache-airflow-providers-postgres>=6.2.1",
]
